export default {
  login: "dannyberns",
  id: 76531652,
  node_id: "MDQ6VXNlcjc2NTMxNjUy",
  avatar_url: "https://avatars.githubusercontent.com/u/76531652?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/dannyberns",
  html_url: "https://github.com/dannyberns",
  followers_url: "https://api.github.com/users/dannyberns/followers",
  following_url:
    "https://api.github.com/users/dannyberns/following{/other_user}",
  gists_url: "https://api.github.com/users/dannyberns/gists{/gist_id}",
  starred_url: "https://api.github.com/users/dannyberns/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/dannyberns/subscriptions",
  organizations_url: "https://api.github.com/users/dannyberns/orgs",
  repos_url: "https://api.github.com/users/dannyberns/repos",
  events_url: "https://api.github.com/users/dannyberns/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/dannyberns/received_events",
  type: "User",
  site_admin: false,
  name: "Danny Bernshtein",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 7,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-12-23T17:19:38Z",
  updated_at: "2021-11-25T18:50:43Z"
};
